apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: taint-tolerations
 labels: 
  purpose: deployment-demo 
  project: roboshop 
spec: 
 replicas: 1
 selector: 
  matchLabels: 
   purpose: deployment-demo 
   project: roboshop 
 template: 
  metadata: 
   labels: 
    purpose: deployment-demo 
    project: roboshop 
  spec: 
   containers: 
   - name: nginx 
     image: nginx:trixie-perl 
